
name: Build ChatGPTWebView IPA

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: xcodebuild -version

      - name: Build .app
        run: |
          xcodebuild \
            -project ChatGPTWebView.xcodeproj \
            -scheme ChatGPTWebView \
            -configuration Release \
            -sdk iphoneos \
            -destination generic/platform=iOS \
            CODE_SIGNING_ALLOWED=NO \
            build

      - name: Debug built .app path
        run: ls -R ~/Library/Developer/Xcode/DerivedData/*/Build/Products/Release-iphoneos/

      - name: Package .ipa
        run: |
          mkdir -p Payload
          cp -r ~/Library/Developer/Xcode/DerivedData/*/Build/Products/Release-iphoneos/ChatGPTWebView.app Payload/
          zip -r ChatGPTWebView.ipa Payload
          rm -rf Payload

      - name: Upload .ipa
        uses: actions/upload-artifact@v4
        with:
          name: ChatGPTWebView-IPA
          path: ChatGPTWebView.ipa
