name: Build ChatGPT WebView IPA

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build .ipa
        run: |
          xcodebuild -project ChatGPTWebView.xcodeproj \
            -scheme ChatGPTWebView \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            clean build \
            CODE_SIGNING_ALLOWED=NO

      - name: Export .ipa
        run: |
          mkdir -p Payload
           cp -r ~/Library/Developer/Xcode/DerivedData/*/Build/Products/Release-iphoneos/ChatGPTWebView.app Payload/
          zip -r ChatGPTWebView.ipa Payload

      - uses: actions/upload-artifact@v4
        with:
          name: ChatGPTWebView-ipa
          path: ChatGPTWebView.ipa
