name: Build and Debug ChatGPTWebView IPA

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: xcodebuild -version

      - name: Build .app with Xcode
        run: |
          xcodebuild \
            -project ChatGPTWebView.xcodeproj \
            -scheme ChatGPTWebView \
            -configuration Release \
            -sdk iphoneos \
            -destination generic/platform=iOS \
            CODE_SIGNING_ALLOWED=NO \
            BUILD_DIR=build

      - name: Find built .app path
        id: find_app
        run: |
          APP_PATH=$(find build -type d -name "ChatGPTWebView.app" | head -n 1)
          echo "Found .app at: $APP_PATH"
          echo "APP_PATH=$APP_PATH" >> "$GITHUB_ENV"

      - name: List contents of .app
        run: |
          ls -lh "$APP_PATH"

      - name: Package .ipa
        run: |
          mkdir -p Payload
          cp -r "$APP_PATH" Payload/
          zip -r ChatGPTWebView.ipa Payload
          rm -rf Payload

      - name: Upload .ipa as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ChatGPTWebView-IPA
          path: ChatGPTWebView.ipa
